# **<center><span style= "color:#C35817;">Naive bayes algorithm</span></center>**

In [1]:
# libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# naive bayes 
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris

In [2]:
# load the dataset
iris = load_iris()
X = iris.data
y = iris.target

In [3]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [5]:
# build the model
gnb = GaussianNB()

# train the model
gnb.fit(X_train,y_train)

# predict the test data
y_pred = gnb.predict(X_test)

# evaluate the model
print("Accuracy : ", accuracy_score(y_test,y_pred))
print("Confusion matrix :\n", confusion_matrix(y_test,y_pred))
print("Classification report : ", classification_report(y_test,y_pred))

Accuracy :  0.9777777777777777
Confusion matrix :
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
Classification report :                precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45

